### ISSUE TITLE
USER STORY: Create a post 

### ISSUE THREAD

**Issue by HPCarey** [HPCarey/trekkers#20]
As a **logged in user** I can **create a new post** so that I can **share my experiences and suggestions for good hikes and walks I’ve been on**.

Acceptance Criteria:
- Add post nav link directs user to an add post form
- The input fields match the posts model in the backend api 
- Input fields include:
                                  - image
                                  -  trail name
                                  - trail description
                                  - locaiton
                                  -  country
                                  -  difficulty/level (dropdown choice)
                                  -  a star rating (could have)
Tasks:
- [x] Create model, serialiser etc and link up urls in backend api
- [x]  Create Post component and make a create post form 
- [x] import star rating component

**Comment by HPCarey** [comment]
Bug: 
Star rating import causing heroku deployment errors because of dependency conflict.
Error message:        npm ERR! code ERESOLVE
       npm ERR! ERESOLVE could not resolve
       npm ERR! 
       npm ERR! While resolving: react-simple-star-rating@4.1.1
       npm ERR! Found: react@17.0.2
       npm ERR! node_modules/react
       npm ERR!   react@"^17.0.2" from the root project
       npm ERR!   peer react@">=16.3.2" from @restart/context@2.1.4
       npm ERR!   node_modules/@restart/context
       npm ERR!     @restart/context@"^2.1.4" from react-bootstrap@1.6.7
       npm ERR!     node_modules/react-bootstrap
       npm ERR!       react-bootstrap@"^1.6.3" from the root project
       npm ERR!   13 more (@restart/hooks, @testing-library/react, ...)
       npm ERR! 
       npm ERR! Could not resolve dependency:
       npm ERR! peer react@">=18.0.0" from react-simple-star-rating@4.1.1
       npm ERR! node_modules/react-simple-star-rating
       npm ERR!   react-simple-star-rating@"^4.1.1" from the root project
       npm ERR! 
       npm ERR! Conflicting peer dependency: react@18.2.0
       npm ERR! node_modules/react
       npm ERR!   peer react@">=18.0.0" from react-simple-star-rating@4.1.1
       npm ERR!   node_modules/react-simple-star-rating
       npm ERR!     react-simple-star-rating@"^4.1.1" from the root project
       npm ERR! 
       npm ERR! Fix the upstream dependency conflict, or retry
       npm ERR! this command with --force, or --legacy-peer-deps
       npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
       npm ERR! 
       npm ERR! See /tmp/npmcache.jBGwF/eresolve-report.txt for a full report.
       
       npm ERR! A complete log of this run can be found in:
       npm ERR!     /tmp/npmcache.jBGwF/_logs/2023-05-23T05_56_50_158Z-debug-0.log
-----> Build failed

**Comment by HPCarey** [comment]
Fixed bug: 
- In package.json, replace engines specific node value with the following for all versions:
"engines": {
        "node": "16.x",
        "npm": "8.5.5"
      }
- Solution found in [this](https://stackoverflow.com/questions/71065040/heroku-shopify-application-error-npm-err-eresolve-unable-to-resolve-dependency) stackoverflow article

**Comment by HPCarey** [comment]
New bug:
- Next build also failed with the following error message: node: bad option: --openssl-legacy-provider
Fixed: 
- Remove --openssl-legacy-provider from scripts.
- Solution source from [this](https://stackoverflow.com/questions/75603337/how-to-fix-node-bad-option-openssl-legacy-provider) stackoverflow article

**Comment by HPCarey** [comment]
Bug: 
- When user creates a post and wishes to select "Easy" as the difficulty level, although "Easy" is the default in the UI, it returns a value of undefined. 
- Suspected backend default value in the model needs to be changed from an empty string to "Easy".
- Changing the default to a string value in the model did not solve the issue

**Comment by HPCarey** [comment]
Fixed Bug:
- Undefined error for first "Easy" choice in difficulty solved by asking ChatGPT and feeding it backend model and frontend form. 
-  ChatGPT suggested defining the default value for difficulty as "Easy" in the inital useState  where we set the post data hook, instead of having an empty string.
- ChatGPT also suggested to make sure the default field in the backend model matches this value, which  I had already changed to a string value of "Easy" so required no further action in the backend.
