### ISSUE TITLE
USER STORY: View post detail

### ISSUE THREAD

**Issue by HPCarey** [HPCarey/trekkers#24]
As a **user** I can **view individual post details** so that I can ** view other details and comments about the post**
 
Acceptance Criteria:
- Any post a user clicks on can be viewed by any user.
- Post detail view will display the post and comments.
- 
Tasks:
- [x] Create Post Detail View
- [x] create a get method
- [x] retrieve a post by its id
